### PR TITLE
Pt team update

### PR DESCRIPTION
**Pull request by patricia-ternes**
Update team members:

- Add David as new director
- Move Patricia from team to Management area
- Move John and Mark to Alumni area

### CODE REVIEW

**Comment by patricia-ternes** [comment]
This PR fixes #229

**Comment by patricia-ternes** [comment]
@TEHardcastle can you see this PR, please?

**Review by TEHardcastle — CHANGES_REQUESTED** [review]
Update Johns bio to reflect his new position.

**Comment by patricia-ternes** [comment]
@TEHardcastle thanks for pointing this out.
I updated the John's position and also used the opportunity to do the same to Martin and Mark.
Please review this PR again.

**Review by TEHardcastle — APPROVED** [review]

**Pull request merged**
