### PR TITLE
Added myself to the team

### PR DESCRIPTION
**Pull request by ajharvie**
Added bio and image to the team page then tidied up the team.yml a bit

### CODE REVIEW

**Comment by patricia-ternes** [comment]
@ajharvie can you ask someone else to review it? As this review is more english than anything else, I think other people are better suited for the job

**Comment by murphyqm** [comment]
Looking at this now!

**Review by murphyqm — APPROVED** [review]
Looks good - no typos.

Tested that it builds locally - all looks correct.

Feel free to merge!

**Comment by patricia-ternes** [comment]
Remember that once this is merged here, it should be also changed in the wordpress.

**Pull request merged**
